// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectHub.Infrastructure.Persistence;

#nullable disable

namespace ProjectHub.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104110436_Add_PrimaryKey")]
    partial class Add_PrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectHub.Domain.Entities.Columns", b =>
                {
                    b.Property<int>("Column_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Column_id"));

                    b.Property<string>("Data_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormulaDefinition")
                        .HasColumnType("text");

                    b.Property<bool>("Is_nullable")
                        .HasColumnType("boolean");

                    b.Property<bool>("Is_primary")
                        .HasColumnType("boolean");

                    b.Property<int?>("LookupRelationshipId")
                        .HasColumnType("integer");

                    b.Property<int?>("LookupTargetColumnId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryKeyType")
                        .HasColumnType("text");

                    b.Property<int>("Table_id")
                        .HasColumnType("integer");

                    b.HasKey("Column_id");

                    b.HasIndex("LookupRelationshipId");

                    b.HasIndex("LookupTargetColumnId");

                    b.HasIndex("Table_id");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Projects", b =>
                {
                    b.Property<int>("Project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Project_id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_id")
                        .HasColumnType("integer");

                    b.HasKey("Project_id");

                    b.HasIndex("User_id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Relationships", b =>
                {
                    b.Property<int>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RelationshipId"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int>("ForeignColumnId")
                        .HasColumnType("integer");

                    b.Property<int>("ForeignTableId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PrimaryColumnId")
                        .HasColumnType("integer");

                    b.Property<int>("PrimaryTableId")
                        .HasColumnType("integer");

                    b.HasKey("RelationshipId");

                    b.HasIndex("ForeignColumnId");

                    b.HasIndex("ForeignTableId");

                    b.HasIndex("PrimaryColumnId");

                    b.HasIndex("PrimaryTableId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Rows", b =>
                {
                    b.Property<int>("Row_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Row_id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Table_id")
                        .HasColumnType("integer");

                    b.HasKey("Row_id");

                    b.HasIndex("Table_id");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Tables", b =>
                {
                    b.Property<int>("Table_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Table_id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Project_id")
                        .HasColumnType("integer");

                    b.HasKey("Table_id");

                    b.HasIndex("Project_id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Users", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("User_id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("User_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Columns", b =>
                {
                    b.HasOne("ProjectHub.Domain.Entities.Relationships", "LookupRelationship")
                        .WithMany()
                        .HasForeignKey("LookupRelationshipId");

                    b.HasOne("ProjectHub.Domain.Entities.Columns", "LookupTargetColumn")
                        .WithMany()
                        .HasForeignKey("LookupTargetColumnId");

                    b.HasOne("ProjectHub.Domain.Entities.Tables", "Tables")
                        .WithMany("Columns")
                        .HasForeignKey("Table_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookupRelationship");

                    b.Navigation("LookupTargetColumn");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Projects", b =>
                {
                    b.HasOne("ProjectHub.Domain.Entities.Users", "Users")
                        .WithMany("Projects")
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Relationships", b =>
                {
                    b.HasOne("ProjectHub.Domain.Entities.Columns", "ForeignColumn")
                        .WithMany()
                        .HasForeignKey("ForeignColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectHub.Domain.Entities.Tables", "ForeignTable")
                        .WithMany()
                        .HasForeignKey("ForeignTableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ProjectHub.Domain.Entities.Columns", "PrimaryColumn")
                        .WithMany()
                        .HasForeignKey("PrimaryColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectHub.Domain.Entities.Tables", "PrimaryTable")
                        .WithMany()
                        .HasForeignKey("PrimaryTableId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ForeignColumn");

                    b.Navigation("ForeignTable");

                    b.Navigation("PrimaryColumn");

                    b.Navigation("PrimaryTable");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Rows", b =>
                {
                    b.HasOne("ProjectHub.Domain.Entities.Tables", "Table")
                        .WithMany("Rows")
                        .HasForeignKey("Table_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Tables", b =>
                {
                    b.HasOne("ProjectHub.Domain.Entities.Projects", "Projects")
                        .WithMany("Tables")
                        .HasForeignKey("Project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Projects", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Tables", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("ProjectHub.Domain.Entities.Users", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
